<h1 align=ltr style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazir" size=6 color="blue" >
Tutorial in Persian
    <br>
    by Reyhane Faraji
    </font>
</h1>

<h1 align=center style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazir" size=10 color="maroon" >
NUMPY
</font>
</h1>

<p dir=rtl style="direction: rtl;text-align: right;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazir" size=4>
نامپاي یک کتابخانه جبر خطی برای پایتون است، به دليل اينکه تقریباً همه کتابخانه‌های مربوط به علم داده در يکي از بلوک‌های خود به آن متکی است، کتابخانه‌ی مهمی برای آن است.
    <br>
    برای استفاده از آن ابتدا باید آن را import کنیم. برای راحتی در طول برنامه نویسی مرسوم است که آن را با حروف اختصاری np وارد می‌کنیم.
    </font>
</p>

In [1]:
import numpy as np

<br>
<div dir=rtl id="start" style="direction:rtl;line-height:200%;">
	<font face="vazir" size=7 color='Red'>
    Array and Matrix
    </font>
</div>

<p dir=rtl style="direction: rtl;text-align: right;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazir" size=4>
 میتوانیم با array و  matrix در np، آرایه و ماتریس را تعریف کنیم:
</font>
</p>

In [2]:
a=np.array([[1,2],[3,4]])
a

array([[1, 2],
       [3, 4]])

In [3]:
b=np.matrix([[1,2],[3,4]])
b

matrix([[1, 2],
        [3, 4]])

<br>
<div dir=rtl id="start" style="direction:rtl;line-height:200%;">
	<font face="vazir" size=6 color='Orange'>
    تفاوت Array و Matrix
    </font>
</div>

<p dir=rtl style="direction: rtl;text-align: right;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazir" size=4>
 1) ماتریس دو بعدی است فقط، ولی array میتواند 1d, 2d, 3d یا بالاتر باشد.
    عملگر .ndim بعد را میدهد
</font>
</p>

In [4]:
A=np.array([1,2,3])
print(A)
print('\nDimension:',A.shape)
print('No. of Dimension:',A.ndim)

[1 2 3]

Dimension: (3,)
No. of Dimension: 1


<p dir=rtl style="direction: rtl;text-align: right;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazir" size=3 color='midnightblue'>
اگر مثال بالا را به جای array با matrix تعریف کنیم، بعد را 2 نشان میدهد زیرا ماتریس همیشه 2 بعدی است.
</font>
</p>

In [5]:
A=np.matrix([1,2,3])
print(A)
print('\nDimension:',A.shape)
print('No. of Dimension:',A.ndim)

[[1 2 3]]

Dimension: (1, 3)
No. of Dimension: 2


<p dir=rtl style="direction: rtl;text-align: right;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazir" size=3 color='midnightblue'>
آرایه دو بعدی و ماتریس دو بعدی مانند هم هستند:
</font>
</p>

In [6]:
B=np.array([[1,2],[3,4]])
print(B)
print('\nDimension:',B.shape)
print('No. of Dimension:',B.ndim)

[[1 2]
 [3 4]]

Dimension: (2, 2)
No. of Dimension: 2


In [7]:
B=np.matrix([[1,2],[3,4]])
print(B)
print('\nDimension:',B.shape)
print('No. of Dimension:',B.ndim)

[[1 2]
 [3 4]]

Dimension: (2, 2)
No. of Dimension: 2


<p dir=rtl style="direction: rtl;text-align: right;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazir" size=3 color='midnightblue'>
آرایه بیشتر از 2 بعد هم داریم ولی ماتریس خیر. مثال زیر با دستور matrix خطا میدهد.
</font>
</p>

In [8]:
C=np.array([[[1,2],[3,4]],[[5,6],[7,8]],[[9,10],[11,12]]])
print(C)
print('\nDimension:',C.shape)
print('No. of Dimension:',C.ndim)

[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]]

Dimension: (3, 2, 2)
No. of Dimension: 3


In [9]:
# C=np.matrix([[[1,2],[3,4]],[[5,6],[7,8]],[[9,10],[11,12]]])

<p dir=rtl style="direction: rtl;text-align: right;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazir" size=4>
2) ماتریس و آرایه رفتار متفاوتی در برابر عملگر * دارند. * دو آرایه را عنصر به عنصر ضرب می کند ولی برای ماتریس، ضرب دو ماتریس را انجام میدهد.
</font>
</p>

In [10]:
a=np.array([[1,2],[3,4]])
b=np.matrix([[1,2],[3,4]])
print('a*a: ',a*a)
print('b*b: ',b*b)

a*a:  [[ 1  4]
 [ 9 16]]
b*b:  [[ 7 10]
 [15 22]]


<p dir=rtl style="direction: rtl;text-align: right;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazir" size=4>
3) عملگر ** برای آرایه هر عنصر را به توان میرساند ولی برای ملتریس ضرب در خود ماتریس میکند.
</font>
</p>

In [11]:
print('a**2: ',a**2)
print('b**2: ',b**2)

a**2:  [[ 1  4]
 [ 9 16]]
b**2:  [[ 7 10]
 [15 22]]


<p dir=rtl style="direction: rtl;text-align: right;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazir" size=4>
4) ماتریس زیرمجموعه آرایه است و تمام روشهای آرایه را ارث بری میکند.
</font>
</p>

<p dir=rtl style="direction: rtl;text-align: right;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazir" size=4>
5) عملگر .I عمل معکوس را برای ماتریس انجام میدهد ولی روی آرایه عمل نمیکند.
</font>
</p>

In [12]:
print(b.I)

[[-2.   1. ]
 [ 1.5 -0.5]]


<p dir=rtl style="direction: rtl;text-align: right;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazir" size=3 color='midnightblue'>
برای معکوس کردن آرایه از عملگر np.linalg.inv() استفاده میکنیم.
</font>
</p>

In [13]:
np.linalg.inv(a)

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

<p dir=rtl style="direction: rtl;text-align: right;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazir" size=4>
6) array class از matrix class بیشتر استفاده میشود.
</font>
</p>

<br>
<div dir=rtl id="start" style="direction:rtl;line-height:200%;">
	<font face="vazir" size=6 color='Orange'>
    عملگرهای آرایه:
    </font>
</div>

<p dir=rtl style="direction: rtl;text-align: right;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazir" size=4>
برای ضرب ماتریسی دو آرایه از عملگر @ استفاده میکنیم.
</font>
</p>

In [14]:
a@a

array([[ 7, 10],
       [15, 22]])

<p dir=rtl style="direction: rtl;text-align: right;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazir" size=4>
عملگر dot هم با دستور زیر همان کار را انجام میدهد.
</font>
</p>

In [15]:
np.dot(a,a)

array([[ 7, 10],
       [15, 22]])

<p dir=rtl style="direction: rtl;text-align: right;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazir" size=4>
عملگر multiply روی آرایه مانند * عمل میکند.
</font>
</p>

In [16]:
np.multiply(a,a)

array([[ 1,  4],
       [ 9, 16]])

<p dir=rtl style="direction: rtl;text-align: right;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazir" size=4>
عملگر prod تمام عناصر آرایه را در هم ضرب میکند.
</font>
</p>

In [17]:
np.prod(a)

24

<p dir=rtl style="direction: rtl;text-align: right;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazir" size=4>
عمل broad casting:
    <br>
    یک عدد را با آرایه جمع میکنیم، عدد را گسترش میدهد و با تک تک عناصر جمع میکند.
</font>
</p>

In [18]:
a=np.array([1,2,3])
a+5

array([6, 7, 8])

<p dir=rtl style="direction: rtl;text-align: right;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazir" size=3 color='midnightblue'>
در جمع یک آرایه 3*1 در 3*3 هم همین اتفاق می افتد.
    <br>
    این گسترش برای چهار عمل اصلی انجام میشود.
</font>
</p>

<p dir=rtl style="direction: rtl;text-align: right;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazir" size=4>
عملگر sum جمع تمام عناصر آرایه را میدهد.
</font>
</p>

In [19]:
np.sum(a)

6

<p dir=rtl style="direction: rtl;text-align: right;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazir" size=4>
عملگر cumsum اولی را در اولین آرایه، جمع اول و دوم را در دومی و جمع اول و دوم و سوم را در سوم میگذارد و همین جور جلو میرود و آرایه ها را با هم جمع میکند..
</font>
</p>

In [20]:
a=np.array([[1,2],[3,4]])
np.cumsum(a)

array([ 1,  3,  6, 10])

<p dir=rtl style="direction: rtl;text-align: right;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazir" size=3 color='midnightblue'>
میتوانیم axis بدهیم. axis=0 برای ستون انجام میدهد و اگر axis=1 باشد برای سطرها انجام میدهد.
    <br>
    axis بالاتر برای آرایه با بعد بالاتر است.
</font>
</p>

In [21]:
np.cumsum(a,axis=0)

array([[1, 2],
       [4, 6]])

In [22]:
np.cumsum(a,axis=1)

array([[1, 3],
       [3, 7]])

<p dir=rtl style="direction: rtl;text-align: right;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazir" size=4>
عملگر subtract روی 2 آرایه، تک تک عناصر آرایه ها را از هم کم میکند.
</font>
</p>

In [23]:
np.subtract(a,a)

array([[0, 0],
       [0, 0]])

<p dir=rtl style="direction: rtl;text-align: right;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazir" size=4>
عملگر divide روی 2 آرایه، تک تک عناصر آرایه ها را تقسیم بر هم میکند. اگر روی یک آرایه و عدد اعمال شود، عناصر آرایه را تقسیم بر عدد میکند.
</font>
</p>

In [24]:
np.divide([5,6,7],3)

array([1.66666667, 2.        , 2.33333333])

<p dir=rtl style="direction: rtl;text-align: right;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazir" size=3 color='midnightblue'>
برای اینکه نتیجه اعداد صحیح باشد:
</font>
</p>

In [25]:
np.floor_divide([5,6,7],3)

array([1, 2, 2], dtype=int32)

<p dir=rtl style="direction: rtl;text-align: right;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazir" size=4>
عملگر sqrt روی اعداد حقیقی اعمال میشود. باید math را هم وارد کنیم.
</font>
</p>

In [26]:
np.math.sqrt(6)

2.449489742783178

<p dir=rtl style="direction: rtl;text-align: right;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazir" size=4>
عملگر size مشخص میکند یک آرایه چند عنصر دارد.
</font>
</p>

In [28]:
np.size(a)

4

<p dir=rtl style="direction: rtl;text-align: right;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazir" size=4>
عملگر shape ابعاد یک آرایه را میدهد.
</font>
</p>

In [29]:
np.shape(a)

(2, 2)

<p dir=rtl style="direction: rtl;text-align: right;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazir" size=4>
تعداد بایت برای هر خانه آرایه
    <br>
    تعداد بایت برای کل آرایه
</font>
</p>

In [30]:
d = np.array(['h', 'e', 'l', 'l', 'o'])
print(d.itemsize)
print(d.nbytes)

4
20


<p dir=rtl style="direction: rtl;text-align: right;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazir" size=4>
عملگر tolist آرایه را به لیست تبدیل میکند.
</font>
</p>

In [31]:
e = np.array([1,2,3,4])
e.tolist()

[1, 2, 3, 4]

<p dir=rtl style="direction: rtl;text-align: right;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazir" size=4>
عملگر flatten ماتریس یا آرایه چند بعدی را تبدیل به یک ماتریس یا عملگر خطی میکند.
    <br>
    یک کپی از آرایه میگیرد و آرایه اولیه را تغییر نمیدهد.
</font>
</p>

In [32]:
a_array = np.array([[1,2,3],[4,5,6],[7,8,9]])
a_array

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [33]:
a_array.flatten()

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

<p dir=rtl style="direction: rtl;text-align: right;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazir" size=3 color='midnightblue'>
عملگر ravel هم همان کار را انجام میدهد با این تفاوت که کپی نمیگیرد و آرایه اولیه را تغییر میدهد.
</font>
</p>

In [34]:
a_array.ravel()

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

<p dir=rtl style="direction: rtl;text-align: right;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazir" size=4>
اگر آرایه را مانند set (مجموعه) در نظر بگیریم، عملگرهای زیر را روی آن اعمال میکنیم:
    </font>
</p>

<p dir=rtl style="direction: rtl;text-align: right;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazir" size=3 color='midnightblue'>
    عملگر unique مقادیر غیرتکراری یک آرایه را میدهد.
</font>
</p>

In [35]:
a = np.array([1,2,3,4,1,3])
np.unique(a)

array([1, 2, 3, 4])

<p dir=rtl style="direction: rtl;text-align: right;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazir" size=3 color='midnightblue'>
    عملگر union1d اتحاد (اجتماع) دو آرایه را میدهد.
</font>
</p>

In [36]:
b = np.array([7,8,9,1,3])
np.union1d(a,b)

array([1, 2, 3, 4, 7, 8, 9])

<p dir=rtl style="direction: rtl;text-align: right;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazir" size=3 color='midnightblue'>
    عملگر intersect1d اشتراک دو آرایه را میدهد.
</font>
</p>

In [37]:
np.intersect1d(a,b)

array([1, 3])

<br>
<div dir=rtl id="start" style="direction:rtl;line-height:200%;">
	<font face="vazir" size=6 color='Orange'>
    ساخت آرایه:
    </font>
</div>

<p dir=rtl style="direction: rtl;text-align: right;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazir" size=4>
از عمگر ones , zeroe  برای ساخت آرایه با عناصر یک و صفر استفاده میکنیم.
    <br>
    اعداد داخل پرانتز تعیین کننده ابعاد آرایه هستند.
</font>
</p>

In [38]:
np.ones((1,3))

array([[1., 1., 1.]])

In [39]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

<p dir=rtl style="direction: rtl;text-align: right;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazir" size=4>
آرایه با مقدار دلخواه:
    <br>
    برای مثال دستور زیر یک آرایه 2*3 با عناصر # ایجاد میکند:
</font>
</p>

In [40]:
np.full((3,2),'#')

array([['#', '#'],
       ['#', '#'],
       ['#', '#']], dtype='<U1')

<p dir=rtl style="direction: rtl;text-align: right;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazir" size=4>
آرایه با مربع با بعد n، متناظر با ماتریش همانی (قطر برابر 1 و بقیه عناصر صفر):

</font>
</p>

In [41]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

<p dir=rtl style="direction: rtl;text-align: right;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazir" size=4>
آرایه 1 بعدی شامل 3 عدد نامشخص (بسته به مقدار داخل حافظه):
</font>
</p>

In [42]:
np.empty(3)

array([1., 1., 1.])

<p dir=rtl style="direction: rtl;text-align: right;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazir" size=4>
مقدار خالی:
</font>
</p>

In [43]:
np.math.nan

nan

<p dir=rtl style="direction: rtl;text-align: right;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazir" size=4>
مقدار بینهایت:
</font>
</p>

In [44]:
np.math.inf

inf

<p dir=rtl style="direction: rtl;text-align: right;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazir" size=4>
آرایه رندم با بعد دلخواه و بین دو عدد دلخواه:
</font>
</p>

In [45]:
np.random.uniform(1,5,(2,3))

array([[4.98011277, 1.74936552, 2.45356378],
       [3.55262689, 3.8457503 , 1.39550138]])

<p dir=rtl style="direction: rtl;text-align: right;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazir" size=4>
آرایه رندم نرمال با دادن بعد:
</font>
</p>

In [46]:
np.random.standard_normal((2,1))

array([[-0.71762832],
       [-0.72352512]])

<p dir=rtl style="direction: rtl;text-align: right;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazir" size=4>
آرایه دو بعدی 3*2 شامل اعداد تصادفی از توزیع نرمال با میانگین 0 و واریانس 1 :
</font>
</p>

In [47]:
np.random.normal(0, 1, (2, 3))

array([[ 0.73315306,  0.62286347, -1.47733943],
       [-0.68899221,  0.6566576 ,  0.44772731]])

<p dir=rtl style="direction: rtl;text-align: right;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazir" size=4>
آرایه یک بعدی شامل 3 عدد تصادفی از توزیع یکنواخت بین 0 و 1:
</font>
</p>

In [48]:
np.random.random(3)

array([0.11049604, 0.8917876 , 0.07974302])

<p dir=rtl style="direction: rtl;text-align: right;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazir" size=4>
آرایه دو بعدی 3*3 شامل اعداد صحیح تصادفی بین 0 تا 9:
</font>
</p>

In [49]:
np.random.randint(0, 10, (3, 3))

array([[2, 5, 3],
       [1, 4, 7],
       [9, 1, 1]])

<p dir=rtl style="direction: rtl;text-align: right;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazir" size=4>
آرایه پر از 3 با ابعاد مشابه آرایه ورودی (3*2):
</font>
</p>

In [50]:
a = np.random.randint(0, 10, (2, 3))
np.full_like(a, 3)

array([[3, 3, 3],
       [3, 3, 3]])

<p dir=rtl style="direction: rtl;text-align: right;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazir" size=4>
میتوانیم برای انتخاب اعداد رندم گزینه بدهیم و وزن یا احتمال برای هر کدام مشخص کنیم:
    <br>
    گزینه ها به صورت لیست در پارامتر p قرار میگیرند و به ترتیب احتمال انتخاب را مشخص میکنند.
</font>
</p>

In [51]:
np.random.choice(['G','S','B'], size=1, p=[0.1, 0.3, 0.6])

array(['S'], dtype='<U1')

<p dir=rtl style="direction: rtl;text-align: right;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazir" size=4>
ساخت دنباله اعداد :
</font>
</p>

<p dir=rtl style="direction: rtl;text-align: right;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazir" size=3 color='midnightblue'>
    (گام، پایان، شروع):
    <br>
از 1 شروع میشه تا قبل 10، 3 تا 3 تا میره:
</font>
</p>

In [52]:
np.arange(1,10,3)

array([1, 4, 7])

<p dir=rtl style="direction: rtl;text-align: right;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazir" size=3 color='midnightblue'>
    (تعداد، پایان، شروع):
    <br>
از 1 شروع میشه تا 10(10 هم شامل میشود) 4 تا عدد میخواهیم (اعداد را با فواصل مساوی میدهد):
</font>
</p>

In [53]:
np.linspace(1,10,4)

array([ 1.,  4.,  7., 10.])

<p dir=rtl style="direction: rtl;text-align: right;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazir" size=4>
فیلتر کردن: از یک آرایه یا ماتریس، مقادیری که میخواهیم را نشان بدهد.
</font>
</p>

In [54]:
my_mask1 = a>2
a[my_mask1]

array([3, 4, 9, 3])

In [55]:
my_mask2 = np.logical_and(a>1,a<4)
a[my_mask2]

array([3, 3])

<p dir=rtl style="direction: rtl;text-align: right;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazir" size=4>
    چند جمله ای ها در نامپای:
    <br>
    میتوان ضرایب یک چند جمله ای را به صورت آرایه تعریف کرد و روی آن عملیات ریاضی مثل جاگذاری مقدار، مشتق و انتگرال اعمال کرد.
    <br>
    چند جمله ای x^2+2x+5 را به صورت زیر تعریف میکنیم:
    </font>
</p>

In [56]:
chandjomleii = np.array([1,2,5]) # 1, 2 & 5 are polynomial coefficients

In [57]:
np.polyval(chandjomleii,1) # Put the value 1 instead of x and calculate the result

8

<p dir=rtl style="direction: rtl;text-align: right;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazir" size=3 color='midnightblue'>
    عملگر polyder مشتق چندجمله ای را حساب میکند و ضرایب را در قالب یک آرایه میدهد.
</font>
</p>

In [58]:
np.polyder(chandjomleii) # x^2+2x+5 ---> 2x+2

array([2, 2])

<p dir=rtl style="direction: rtl;text-align: right;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazir" size=3 color='midnightblue'>
    عملگر polyint انتگرال چندجمله ای را حساب میکند و ضرایب را در قالب یک آرایه میدهد.
</font>
</p>

In [59]:
np.polyint(chandjomleii) # x^2+2x+5 ---> 1/3 x^3+x^2+5x+0

array([0.33333333, 1.        , 5.        , 0.        ])

<br>
<div dir=rtl id="start" style="direction:rtl;line-height:200%;">
	<font face="vazir" size=6 color='Orange'>
    نوع داده:
    </font>
</div>

<p dir=rtl style="direction: rtl;text-align: right;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazir" size=4>
عملگردر آرایه نامپای، نوع داده داخل خانه‌ها یکسان است و موقع ساخت آرایه مشخص می‌شود. نوع این داده‌ها می‌تواند از انواع مختلفی چون عدد حقیقی، عدد صحیح، مقدار بولی و رشته باشد. تعیین نوع خانه‌ها از روی ورودی را می‌توان به نامپای سپرد و یا با تعیین پارامتر dtype آن را مشخص کرد..
</font>
</p>

<p dir=rtl style="direction: rtl;text-align: right;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazir" size=4>
نوع مقدار بولی
</font>
</p>

<p dir=rtl style="direction: rtl;text-align: right;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazir" size=3 color='midnightblue'>
کاراکتر _ برای اشاره به نوع داخل نامپای است اما می‌توان آن را برداشت
</font>
</p>

In [60]:
np.array([False, True], dtype='bool_')

array([False,  True])

<p dir=rtl style="direction: rtl;text-align: right;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazir" size=4>
نوع عدد صحیح (عدد سوم تبدیل به 3 می‌شود)
</font>
</p>

In [61]:
np.array([1, 2, 3.14], dtype='int_')

array([1, 2, 3])

<p dir=rtl style="direction: rtl;text-align: right;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazir" size=4>
نوع عدد حقیقی 64 بیتی
</font>
</p>

In [62]:
np.array([2.71828182845, 3.14159265359], dtype='float64')

array([2.71828183, 3.14159265])

<p dir=rtl style="direction: rtl;text-align: right;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazir" size=4>
نوع عدد صحیح نامنفی 8 بیتی
</font>
</p>

In [63]:
np.array([255], dtype='uint8')

array([255], dtype=uint8)

<p dir=rtl style="direction: rtl;text-align: right;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazir" size=4>
نوع رشته
</font>
</p>

In [64]:
np.array(['Hello', 'World'], dtype='str_')

array(['Hello', 'World'], dtype='<U5')

<br>
<div dir=rtl id="start" style="direction:rtl;line-height:200%;">
	<font face="vazir" size=7 color='Red'>
    کار با آرایه
    </font>
</div>

<br>
<div dir=rtl id="start" style="direction:rtl;line-height:200%;">
	<font face="vazir" size=6 color='Orange'>
    نمایه سازی (indexing)
    </font>
</div>

<p dir=rtl style="direction: rtl;text-align: right;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazir" size=4>
برای دسترسی به یک خانه دلخواه آرایه، می‌توان مختصات آن را داخل <code>[]</code> قرار داد. مشابه لیست پایتون، شماره‌ها از صفر آغاز می‌شوند و شماره منفی به معنای شروع از انتهای آرایه است.
</font>
</p>

In [65]:
a = np.array([0, 1, 2, 3])
print(a)
print('a[0] =', a[0])
print('a[2] =', a[2])
print('a[-1] =', a[-1])

[0 1 2 3]
a[0] = 0
a[2] = 2
a[-1] = 3


In [66]:
a = np.random.randint(0, 10, (3, 5))
print(a)
print('a[2, 3] =', a[2, 3])

[[1 0 0 3 5]
 [9 8 0 9 0]
 [1 1 6 0 7]]
a[2, 3] = 0


<p dir=rtl style="direction: rtl;text-align: right;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazir" size=3 color='midnightblue'>
می‌توانیم مقدار یک خانه را ضمن دسترسی به آن تغییر دهیم.
</font>
</p>

In [67]:
a[2, 3] = 10
print('a[2, 3] =', a[2, 3])

a[2, 3] = 10


<p dir=rtl style="direction: rtl;text-align: right;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazir" size=3 color='midnightblue'>
چون آرایه نوع داده مشخصی دارد، مقداری که داخل یک خانه آن قرار می‌دهید در صورت امکان به نوع داده آرایه تبدیل می‌شود. برای مثال اگر در یک آرایه از جنس اعداد صحیح یک مقدار حقیقی قرار دهید، بخش صحیح عدد داخل آرایه قرار می‌گیرد.
</font>
</p>

In [68]:
a[2, 3] = 3.14
print('a[2, 3] =', a[2, 3])

a[2, 3] = 3


<br>
<div dir=rtl id="start" style="direction:rtl;line-height:200%;">
	<font face="vazir" size=6 color='Orange'>
    برش (slicing)
    </font>
</div>

<p dir=rtl style="direction: rtl;text-align: right;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazir" size=4>
برای دسترسی به زیرآرایه‌های یک آرایه نامپای، می‌توان مثل لیست پایتون آن را برش داد و ابتدای برش، انتهای برش و گام‌ برش را با دونقطه (:) از هم جدا کرد. در صورت مشخص نکردن این مقادیر، مقدار پیش‌فرض (صفر برای شروع، اندازه آرایه برای پایان و یک برای گام پرش) برای هر یک لحاظ می‌شود.
</font>
</p>

In [69]:
a = np.array([0, 1, 2, 3, 4])
print(a[:3])
print(a[2:4])
print(a[1:5:2])
print(a[::-1])

[0 1 2]
[2 3]
[1 3]
[4 3 2 1 0]


<p dir=rtl style="direction: rtl;text-align: right;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazir" size=3 color='midnightblue'>
b برابر با ردیف 0 و 1، ستون 1 تا آخر
    <br>
    c برابر با ردیف 1 و 2، تمام ستونها با گام 2
    <br>
    d همه ردیفها، ستون 1
</font>
</p>

In [70]:
a = np.array([[0, 1, 2],
             [3, 4, 5],
             [6, 7, 8],
             [9, 10, 11]])
b=a[:2, 1:]
c=a[1:3, ::2]
d=a[:,1]
a[2,:]=a[2]
print(b)
print(c)
print(d)

[[1 2]
 [4 5]]
[[3 5]
 [6 8]]
[ 1  4  7 10]


<p dir=rtl style="direction: rtl;text-align: right;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazir" size=3 color='midnightblue'>
با تغییر دادن زیرآرایه حاصل، آرایه اصلی هم تغییر می‌کند.
</font>
</p>

In [71]:
a = np.array([[0, 1, 2],
             [3, 4, 5],
             [6, 7, 8]])
sub_a = a[1:3, 1:]
sub_a[0, 0] = 10
print(a)

[[ 0  1  2]
 [ 3 10  5]
 [ 6  7  8]]


<p dir=rtl style="direction: rtl;text-align: right;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazir" size=4>
برای کپی گرفتن از یک آرایه متد copy را صدا میزنیم.
</font>
</p>

In [72]:
a = np.array([[0, 1, 2],
             [3, 4, 5],
             [6, 7, 8]])
sub_copy_a = a[2:4, 1:].copy()
sub_copy_a[0, 0] = 10
print(a)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


<br>
<div dir=rtl id="start" style="direction:rtl;line-height:200%;">
	<font face="vazir" size=6 color='Orange'>
    بازآرایی و ترانهادن
    </font>
</div>

<p dir=rtl style="direction: rtl;text-align: right;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazir" size=4>
یک آرایه از پیش تعریف شده را می‌توان بازآرایی کرد و به آن ابعاد تازه‌ای داد؛ به شرط آن که اندازه آرایه برابر با اندازه حاصل از ابعاد داده‌شده باشد. برای این منظور کافیست متد reshape را برای آرایه صدا بزنیم و اندازه ابعاد تازه را در قالب یک چندتایی یا یک عدد (برای آرایه تک‌بعدی) به آن ورودی دهیم.
</font>
</p>

In [73]:
a = np.arange(16)
print(a)
print(a.reshape(4, 4))

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


In [74]:
a = np.array([1, 2, 3])
print(a.reshape(3, 1))
print(a.reshape(1, 3))

[[1]
 [2]
 [3]]
[[1 2 3]]


<p dir=rtl style="direction: rtl;text-align: right;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazir" size=3 color='midnightblue'>
اگر برای بازآرایی اندازه دقیقا یکی از بعدها را 1- ورودی دهیم، نامپای از روی اندازه آرایه و اندازه سایر ابعاد ورودی، اندازه آن بعد را هم تشخیص می‌دهد.
</font>
</p>

In [75]:
a = np.arange(12)
print(a.reshape(2, -1, 3))

[[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]]


<p dir=rtl style="direction: rtl;text-align: right;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazir" size=4>
ترتیب ابعاد یک آرایه را هم می‌توان تغییر داد. با صدا زدن متد T یا transpose (بدون ورودی) ترتیب ابعاد آرایه برعکس می‌شود. برای مثال با برعکس کردن بعدهای یک آرایه دوبعدی جای سطرها و ستون‌های آن عوض می‌شود. بنابراین اگر آرایه دوبعدی را یک ماتریس در نظر بگیریم، ماتریس ترانهاده به دست می‌آید.
</font>
</p>

In [76]:
a = np.arange(8).reshape(2, 4)
print(a)
print(a.T)

[[0 1 2 3]
 [4 5 6 7]]
[[0 4]
 [1 5]
 [2 6]
 [3 7]]


<p dir=rtl style="direction: rtl;text-align: right;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazir" size=3 color='midnightblue'>
می‌توان ترتیب دلخواهی را هم با ورودی دادن به متد transpose اعمال کرد.
    <br>
    a سه بعد دارد که به ترتیب اندازه‌های 2، 3 و 4 دارند و برای اشاره به هر خانه از آن به ترتیب باید مختصات خانه در این بعدها را تعیین کنیم. برای مثال عدد 23 در خانه a[1, 2, 3]‍ قرار دارد. حال اگر متد transpose را برای a صدا بزنیم و ترتیب تازه‌ای را به آن ورودی دهیم، ترتیب بعدها تغییر می‌کند.
</font>
</p>

In [77]:
a = np.arange(24).reshape(2, 3, 4)
print(a)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


<p dir=rtl style="direction: rtl;text-align: right;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazir" size=3 color='midnightblue'>
در کد زیر با صدا زدن a.transpose(1, 2, 0)، بُعد دوم (شماره 1) تبدیل به بُعد اول آرایه جدید، بُعد سوم (شماره 2) تبدیل به بُعد دوم آرایه جدید و بُعد نخست (شماره 0) تبدیل به بُعد سوم آرایه جدید می‌شود. به این ترتیب اندازه ابعاد آرایه جدید به ترتیب 3، 4 و 2 خواهد بود و عدد 23 این بار در خانه [2, 3, 1] قرار می‌گیرد.
</font>
</p>

In [78]:
a.transpose(1, 2, 0)

array([[[ 0, 12],
        [ 1, 13],
        [ 2, 14],
        [ 3, 15]],

       [[ 4, 16],
        [ 5, 17],
        [ 6, 18],
        [ 7, 19]],

       [[ 8, 20],
        [ 9, 21],
        [10, 22],
        [11, 23]]])

<p dir=rtl style="direction: rtl;text-align: right;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazir" size=3 color='midnightblue'>
اگر تنها بخواهیم تنها دو تا از بعدها را با هم جابجا کنیم می‌توانیم از متد swapaxes استفاده کنیم و شماره دو بعد آرایه (با شروع از 0) را به آن ورودی دهیم.
    <br>
    کلمه axes در این متد اسم جمع کلمه axis به معنای محور است.
</font>
</p>

In [79]:
a.swapaxes(0, 2)

array([[[ 0, 12],
        [ 4, 16],
        [ 8, 20]],

       [[ 1, 13],
        [ 5, 17],
        [ 9, 21]],

       [[ 2, 14],
        [ 6, 18],
        [10, 22]],

       [[ 3, 15],
        [ 7, 19],
        [11, 23]]])

<img src='./1.Numpy_file/01.jpg'/>

<br>
<div dir=rtl id="start" style="direction:rtl;line-height:200%;">
	<font face="vazir" size=6 color='Orange'>
    به هم دوختن و شکافتن آرایه‌ها
    </font>
</div>

<p dir=rtl style="direction: rtl;text-align: right;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazir" size=4>
برای به هم دوختن چند آرایه می‌توان از تابع concatenate استفاده کرد. به این شکل که در یک لیست تعدادی آرایه به آن می‌دهیم تا آرایه‌ها را در جهت محوری که با پارامتر axis مشخص می‌شود (به طور پیش‌فرض محور نخست) به هم بدوزد. آرایه‌های داده‌شده باید در جهت سایر محورها ابعاد یکسانی داشته باشند. 
</font>
</p>

In [80]:
x = np.arange(6).reshape(2, 3)
y = np.arange(6, 12).reshape(2, 3)
z = np.arange(12, 15).reshape(1, 3)
np.concatenate([x, y, z])

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [81]:
np.concatenate([x, y], axis=1)

array([[ 0,  1,  2,  6,  7,  8],
       [ 3,  4,  5,  9, 10, 11]])

<img src='./1.Numpy_file/02.jpg'/>

<p dir=rtl style="direction: rtl;text-align: right;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazir" size=4>
با متد split یک آرایه را در جهت محوری که با پارامتر axis مشخص میکنیم، از نقاطی که با یک لیست داده مشود، میشکافد.
</font>
</p>

In [82]:
a = np.arange(10)
x, y, z = np.split(a, [2, 5])
print(x)
print(y)
print(z)

[0 1]
[2 3 4]
[5 6 7 8 9]


<p dir=rtl style="direction: rtl;text-align: right;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazir" size=3 color='midnightblue'>
به جای نقطه برش میتوان عدد داد تا آرایه تقسیم بر آن تعداد شود. باید اندازه بعد آرایه در راستای محور axis بر این عدد بخشپذیر باشد.
</font>
</p>

In [83]:
a = np.arange(12).reshape(2, 6)
x, y, z = np.split(a, 3, axis=1)
print(x)
print(y)
print(z)

[[0 1]
 [6 7]]
[[2 3]
 [8 9]]
[[ 4  5]
 [10 11]]


<p dir=rtl style="direction: rtl;text-align: right;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazir" size=3 color='midnightblue'>
بعد از برش اگر فقط بخش دوم را بخواهیم از دستور زیر استفاده میکنیم.
</font>
</p>

In [84]:
a = np.arange(12).reshape(2, 6)
y = np.split(a,2)[1]
print(y)

[[ 6  7  8  9 10 11]]


<br>
<div dir=rtl id="start" style="direction:rtl;line-height:200%;">
	<font face="vazir" size=7 color='Red'>
    توابع عمومی (Ufuncs)
    </font>
</div>

<p dir=rtl style="direction: rtl;text-align: right;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazir" size=4>
عمل‌هایی که عملیات‌ برداری (vectorized operations) نامیده می‌شوند با استفاده از توابع نامپای بسیار سریع‌تر انجام می‌شوند. کتابخانه نامپای برای این منظور توابع عمومی (universal functions یا به اختصار ufuncs) را پیش‌بینی کرده است.
</font>
</p>

<p dir=rtl style="direction: rtl;text-align: right;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazir" size=4>
توابع عمومی دو عملوندی (binary ufuncs): (عملیات را روی دو آرایه انجام می‌دهند)
</font>
</p>

<p dir=rtl style="direction: rtl;text-align: right;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazir" size=3 color='midnightblue'>
تابع add دو آرایه ورودی را عنصر به عنصر با هم جمع می‌کند:
</font>
</p>

In [85]:
a = np.array([0, 1, 2, 3])
b = np.array([-2, 10, 1, 5])
print('a + b =', np.add(a, b)) 
print('a + b =', a + b) # است a + b معادل np.add(a, b)

a + b = [-2 11  3  8]
a + b = [-2 11  3  8]


<p dir=rtl style="direction: rtl;text-align: right;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazir" size=3 color='midnightblue'>
تابع subtract دو آرایه ورودی را عنصر به عنصر از هم کم می‌کند:
</font>
</p>

In [88]:
print('a - b =', np.subtract(a, b)) 
print('a - b =', a - b) # است a - b معادل np.subtract(a, b)

a - b = [ 2 -9  1 -2]
a - b = [ 2 -9  1 -2]


<p dir=rtl style="direction: rtl;text-align: right;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazir" size=3 color='midnightblue'>
تابع multiply دو آرایه ورودی را عنصر به عنصر در هم ضرب می‌کند:
</font>
</p>

In [89]:
print('a * b =', np.multiply(a, b)) 
print('a * b =', a * b) # است a * b معادل np.multiply(a, b)

a * b = [ 0 10  2 15]
a * b = [ 0 10  2 15]


<p dir=rtl style="direction: rtl;text-align: right;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazir" size=3 color='midnightblue'>
تابع divide دو آرایه ورودی را عنصر به عنصر بر هم تقسیم می‌کند:
</font>
</p>

In [90]:
print('a / b =', np.divide(a, b)) 
print('a / b =', a / b) # است a / b معادل np.divide(a, b)

a / b = [-0.   0.1  2.   0.6]
a / b = [-0.   0.1  2.   0.6]


<p dir=rtl style="direction: rtl;text-align: right;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazir" size=4>
توابع عمومی تک عملوندی: (عملیات را روی یک آرایه انجام می‌دهند)
</font>
</p>

<p dir=rtl style="direction: rtl;text-align: right;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazir" size=3 color='midnightblue'>
تابع abs قدرمطلق مقادیر یک آرایه را محاسبه می‌کند:
</font>
</p>

In [91]:
a = [4, 8, 3, 6, 6]
b = [-8,  6, -7,  6,  1]
print('absolute values of b =', np.abs(b)) 

absolute values of b = [8 6 7 6 1]


<p dir=rtl style="direction: rtl;text-align: right;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazir" size=3 color='midnightblue'>
تابع square توان دوم عناصر یک آرایه را محاسبه می‌کند:
</font>
</p>

In [92]:
print('square values of a =', np.square(a) ) 

square values of a = [16 64  9 36 36]


<p dir=rtl style="direction: rtl;text-align: right;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazir" size=3 color='midnightblue'>
تابع sqrt ریشه دوم عناصر یک آرایه را محاسبه می‌کند:
    <br>
    تابع isnan، رای نشان دادن عدد نبودن مقدار یک خانه در آرایه عددی استفاده می‌شود. nan بودن عناصر یک آرایه عدد را مشخص می کند:
</font>
</p>

In [93]:
np.seterr(invalid="ignore") # خطای ناشی از عملیات غیرمجاز را نادیده می‌گیرد
a = np.array([1 , 2 , -3 , 4, -5])
print('a = ', a)
print('isnan results for a =', np.isnan(a))
print('sqrt(a) = ', np.sqrt(a))
print('isnan resultes for sqrt(a) =', np.isnan(np.sqrt(a)))

a =  [ 1  2 -3  4 -5]
isnan results for a = [False False False False False]
sqrt(a) =  [1.         1.41421356        nan 2.                nan]
isnan resultes for sqrt(a) = [False False  True False  True]


<br>
<div dir=rtl id="start" style="direction:rtl;line-height:200%;">
	<font face="vazir" size=7 color='Red'>
    توابع تجمیعی
    </font>
</div>

<p dir=rtl style="direction: rtl;text-align: right;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazir" size=4>
برای توصیف داده معمولا از آماره هایی چون میانگین و انحراف معیار استفاده می‌شود که داده را در قالب اعداد توصیف می‌کنند. به توابعی از این دست که درباره یک مجموعه از داده یک عدد گزارش می‌کنند، توابع تجمیعی می‌گوییم. توابعی چون مجموع (sum) ، کمینه (min) و بیشینه (max)
</font>
</p>

In [94]:
a = np.random.randint(0, 10, 20)
print(a)
print('sum =', np.sum(a))
print('min =', np.min(a))
print('max =', np.max(a))

[4 0 4 6 1 4 8 0 6 8 5 5 2 7 7 6 3 5 6 7]
sum = 94
min = 0
max = 8


<p dir=rtl style="direction: rtl;text-align: right;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazir" size=3 color='midnightblue'>
برخی از این توابع به شکل متدهایی برای آرایه هم موجود هستند و می‌توان به شکل زیر از آن‌ها استفاده کرد.
</font>
</p>

In [95]:
print(a.min(), a.max(), a.sum())

0 8 94


<p dir=rtl style="direction: rtl;text-align: right;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazir" size=4>
با تعیین محور تجمیع می‌توان این کار را در راستای تنها یک محور هم انجام داد. برای مثال اگر یک آرایه دو بعدی داشته باشیم و بخواهیم مقدار کمینه ستون‌ها را به صورت یک آرایه داشته باشیم، کافیست متد min را با ورودی axis=0 برای آرایه صدا بزنیم. چرا که بُعد مربوط به سطرها که می‌خواهیم تجمیع‌شده و از بین برود، هم‌راستا با محور شماره 0 است. به این ترتیب خروجی آرایه‌ایست یک بُعدی که به ازای هر ستون کمینه خانه‌های آن ستون در سطرهای مختلف قرار گرفته است (به طور کلی شکل خروجی شبیه آرایه ابتداییست، با این تفاوت که بُعدی از آن، که در جهت محور axis است تجمیع شده و از بین رفته‌است).
</font>
</p>

In [96]:
a = np.random.randint(0, 10, (3, 4))
a.min(axis=0)

array([1, 0, 6, 3])

In [97]:
a.max(axis=1)

array([9, 9, 7])

<img src='./1.Numpy_file/03.jpg'/>

<p dir=rtl style="direction: rtl;text-align: right;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazir" size=3 color='midnightblue'>
تابع percentile چارک ها را حساب میکند.
    <br>
    np.var واریانس عناصر را محاسبه می‌کند.
    <br>
    np.median میانه عناصر را محاسبه میکند.
    <br>
    np.std انحراف معیار را محاسبه میکند.
    <br>
np.argmin شماره خانه کمینه را برمی‌گرداند.
    <br>
np.argmax شماره خانه بیشینه را برمی‌گرداند.	
</font>
</p>

In [98]:
heights = np.array([[194, 185, 183, 184, 178, 178, 190, 187, 187, 179, 186], 
                    [192, 173, 194, 184, 170, 189, 170, 170, 176, 173, 185]])
print('Iran vs Spain')
print('Mean height:', heights.mean(axis=1))
print('Standard deviation:', heights.std(axis=1))
print('25th percentile:', np.percentile(heights, 25, axis=1)) 

Iran vs Spain
Mean height: [184.63636364 179.63636364]
Standard deviation: [4.79152144 8.91650897]
25th percentile: [181.  171.5]


<br>
<div dir=rtl id="start" style="direction:rtl;line-height:200%;">
	<font face="vazir" size=7 color='Red'>
    پخش آرایه
    </font>
</div>

<p dir=rtl style="direction: rtl;text-align: right;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazir" size=4>
وقتی یک عدد ثابت را در یک آرایه ضرب میکنیم، انگار عدد به صورت آرایه یک بعدی در می آید و عنصر به عنصر در آرایه ضرب میشود.
    <br>
    اگر آرایه دو بعدی را با یک بعدی جمع کنیم (با ستونهای برابر) همین تفاق می افتد.
</font>
</p>

In [99]:
a = np.arange(12).reshape(3, 4)
print(a)
b = np.array([3, 2, 1, 0])
print(b)
a + b

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[3 2 1 0]


array([[ 3,  3,  3,  3],
       [ 7,  7,  7,  7],
       [11, 11, 11, 11]])

<p dir=rtl style="direction: rtl;text-align: right;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazir" size=3 color='midnightblue'>
گاهی هم هر دو آرایه پخش میشوند تا ابعادشان برابر شود.
</font>
</p>

In [100]:
a = np.array([1, 2, 3, 4, 5])
b = np.array([1, 2, 3, 4]).reshape(4, 1)
print(a)
print(b)
a * b

[1 2 3 4 5]
[[1]
 [2]
 [3]
 [4]]


array([[ 1,  2,  3,  4,  5],
       [ 2,  4,  6,  8, 10],
       [ 3,  6,  9, 12, 15],
       [ 4,  8, 12, 16, 20]])

<p dir=rtl style="direction: rtl;text-align: right;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazir" size=3 color='midnightblue'>
به طور کلی قانون دقیق پخش شدن آرایه‌ها برای هم‌اندازه شدن به شکل زیر است:
    <br>
اگر دو آرایه هم‌مرتبه (با تعداد بُعد برابر) نبودند، به ابتدای ابعاد آرایه با مرتبه کوچک‌تر تعدادی بعد با اندازه ۱ اضافه کن تا جایی که هم‌مرتبه شوند.
    <br>
اگر اندازه دو آرایه در بُعدی برابر نبود، آرایه‌ای که اندازه آن بُعدش ۱ است را در جهت محور آن بُعد بکش تا مثل آرایه دیگر شود.
    <br>
اگر اندازه دو آرایه در بُعدی برابر نبود و اندازه هیچ‌یک در آن بُعد برابر با ۱ نبود، پیام خطا بده.
</font>
</p>

<br>
<div dir=rtl id="start" style="direction:rtl;line-height:200%;">
	<font face="vazir" size=7 color='Red'>
    مقایسه و منطق بولی
    </font>
</div>

<p dir=rtl style="direction: rtl;text-align: right;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazir" size=4>
نوع دیگری از عملیات‌ روی آرایه‌ها که کاربرد زیادی دارند، عملیات‌ مقایسه‌ای هستند. خروجی مقایسه دو آرایه، یک آرایه از جنس مقدار بولی است که در هر خانه آن حاصل مقایسه عناصر متناظر دو آرایه قرار می‌گیرد. دقت کنید که دو آرایه مقایسه شونده ممکن است هم‌شکل نباشند و در آن صورت حاصل مقایسه هم‌شکل شده آن‌ها به کمک خاصیت پخش آرایه‌ها (broadcasting) خروجی داده می‌شود (ابعاد آرایه خروجی هم مشابه آرایه‌های هم‌شکل شده خواهد بود). 
</font>
</p>

<img src='./1.Numpy_file/04.jpg'/>

In [101]:
a = np.array([2, 13, -5, -3, 19, -17])
a < 7 # سمت راست مقایسه به شکل یک آرایه (,6) با مقادیر 7 در می‌آید

array([ True, False,  True,  True, False,  True])

In [102]:
a == np.sqrt(a ** 2)  # دو سمت مقایسه می‌توانند هم‌نوع نباشند اما مقایسه‌پذیر باشند

array([ True,  True, False, False,  True, False])

<br>
<div dir=rtl id="start" style="direction:rtl;line-height:200%;">
	<font face="vazir" size=6 color='Orange'>
    توابع مخصوص آرایه‌های بولی
    </font>
</div>

<p dir=rtl style="direction: rtl;text-align: right;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazir" size=4>
اگر بخواهیم در یک آرایه مثلا اعداد بزرگتر از 20 را بشماریم از تابع np.count_nonzero استفاده میکنیم. این توابع False را صفر و True را یک در نظر میگیرند. برای این کار از تابع np.sum هم میتوانیم استفاده کنیم.
</font>
</p>

In [103]:
# آرایه دو بعدی t با ابعاد (7 ,4) دمای روزانه هوای شهر شیراز 
# طی هفت روز هفته را در چهار هفته ماه اردیبهشت به سانتی‌گراد نشان می‌دهد.
t = np.array([[10, 12, 11, 17, 15, 11, 14],
             [13, 15, 18, 21, 19, 18, 17],
             [18, 20, 21, 19, 23, 24, 22],
             [20, 23, 19, 21, 25, 22, 21]])
t > 20 # خروجی یک آرایه (7 ,4) با مقادیر بولی است

array([[False, False, False, False, False, False, False],
       [False, False, False,  True, False, False, False],
       [False, False,  True, False,  True,  True,  True],
       [False,  True, False,  True,  True,  True,  True]])

In [104]:
np.count_nonzero(t > 20)

10

In [105]:
np.sum(t > 20)

10

<p dir=rtl style="direction: rtl;text-align: right;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazir" size=3 color='midnightblue'>
با مشخص کردن محور محاسبه می‌توانیم تعداد روزهای با دمای بالاتر از ۲۰ را به تفکیک هفته‌ها هم محاسبه کنیم.
</font>
</p>

In [106]:
np.sum(t > 20, axis=1)

array([0, 1, 4, 5])

<p dir=rtl style="direction: rtl;text-align: right;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazir" size=4>
    از تابع np.any برای بررسی True بودن حداقل یک خانه و از تابع np.all  برای بررسی True بودن تمام خانه ها استفاده میکنیم.
</font>
</p>

In [107]:
np.any(t > 30)

False

In [108]:
np.all(t >= 10)

True

<br>
<div dir=rtl id="start" style="direction:rtl;line-height:200%;">
	<font face="vazir" size=6 color='Orange'>
    عملیات‌ منطق بولی
    </font>
</div>

<img src='./1.Numpy_file/05.jpg'/>

<p dir=rtl style="direction: rtl;text-align: right;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazir" size=4>
    برای مثال، در مسئله قبلی برای شمردن تعداد روزهای ماه با دمای بین ۱۵ و ۲۰ می‌توان دو مقایسه را به صورت جداگانه انجام داد و با وَ (and‍‍‍) بیتی گرفتن از دو آرایه حاصل به آرایه دیگری رسید که در آن خانه‌های متناظر با روزهای مدنظرمان True هستند. این کار را می‌توان با ترکیب عملگرهای یا (or) و وارون (not) بیتی هم انجام داد.
</font>
</p>

In [109]:
np.sum((t >= 15) & (t <= 20))

12

In [110]:
np.sum(~((t < 15) | (t > 20)))

12

<br>
<div dir=rtl id="start" style="direction:rtl;line-height:200%;">
	<font face="vazir" size=7 color='Red'>
    نمایه‌سازی با آرایه‌ها
    </font>
</div>

<br>
<div dir=rtl id="start" style="direction:rtl;line-height:200%;">
	<font face="vazir" size=6 color='Orange'>
    نمایه‌سازی با آرایه‌های بولی (boolean indexing)
    </font>
</div>

<p dir=rtl style="direction: rtl;text-align: right;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazir" size=4>
    با قابلیت نمایه سازی (indexing) از آرایه ها به وسیله آرایه های بولی، میتوانیم به یک زیرمجموعه از آرایه که ویژگی مشخصی دارند دسترسی پیدا کنیم.
</font>
</p>

In [111]:
t = np.array([[10, 12, 11, 17, 15, 11, 14],
             [13, 15, 18, 21, 19, 18, 17],
             [18, 20, 21, 19, 23, 24, 22],
             [20, 23, 19, 21, 25, 22, 21]])
t[(t >= 15) & (t <= 20)]

array([17, 15, 15, 18, 19, 18, 17, 18, 20, 19, 20, 19])

<p dir=rtl style="direction: rtl;text-align: right;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazir" size=4>
    می‌توانیم در داخل [] جلوی نام آرایه، یک آرایه بولی هم‌شکل آرایه قرار دهیم. در نتیجه آن، یک آرایه یک بعدی شامل عناصری از آرایه برگردانده می‌شود که خانه متناظرشان در آرایه بولی مقدار True داشته باشد. به این کار اصطلاحا masking هم می‌گویند.
</font>
</p>

In [112]:
print('میانگین دمای هوا در روزهای گرم‌تر از ۲۰ درجه:', t[t > 20].mean())
print('میانه دمای هوا در روزهای سردتر از ۲۰ و گرم‌تر از ۱۵ درجه:', np.median(t[(t > 15) & (t < 20)]))

میانگین دمای هوا در روزهای گرم‌تر از ۲۰ درجه: 22.3
میانه دمای هوا در روزهای سردتر از ۲۰ و گرم‌تر از ۱۵ درجه: 18.0


In [113]:
calendar = np.arange(4*7).reshape(4, 7)
holidays = (calendar%7 >= 5) # آرایه بولی متناظر روزهای آخر هفته (پنج‌شنبه و جمعه)
first_mid = (calendar < 2*7) # آرایه بولی متناظر روزهای دو هفته اول اردیبهشت
print('میانه دمای روزهای آخرِ هفته کل ماه:', np.median(t[holidays]))
print('میانه دمای دو هفته نخست ماه:', np.median(t[first_mid]))
print('میانگین دمای روزهای آخرِ هفته در دو هفته پایانی ماه:', np.mean(t[~first_mid & holidays]))

میانه دمای روزهای آخرِ هفته کل ماه: 19.5
میانه دمای دو هفته نخست ماه: 15.0
میانگین دمای روزهای آخرِ هفته در دو هفته پایانی ماه: 22.25


<br>
<div dir=rtl id="start" style="direction:rtl;line-height:200%;">
	<font face="vazir" size=6 color='Orange'>
نمایه‌سازی با آرایه‌های عددی (fancy indexing)
    </font>
</div>

<p dir=rtl style="direction: rtl;text-align: right;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazir" size=4>
    مثلا در یک آرایه، خانه های شماره 2 و 3 و 5 را بخواهیم.
</font>
</p>

In [114]:
a = np.array([1, 2, 4, 8, 16, 32])
ind = [2, 3, 5]
a[ind]

array([ 4,  8, 32])

<p dir=rtl style="direction: rtl;text-align: right;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazir" size=3 color='midnightblue'>
میتوانیم آرایه ind را دو بعدی تعریف کنیم و در هر خانه آن مقدار خانه‌ای از آرایه اصلی که در ind به شماره آن اشاره شده قرار می‌گیرد.
    </font>
</p>

In [115]:
ind = np.array([[2, 3],
               [4, 1]])
a[ind]

array([[ 4,  8],
       [16,  2]])

<p dir=rtl style="direction: rtl;text-align: right;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazir" size=4>
این شکل از نمایه‌سازی را برای آرایه‌های چندبعدی هم می‌توان انجام داد. برای این منظور، مختصات خانه‌هایی که می‌خواهیم را برای هر بُعد جدا می‌کنیم و در یک آرایه نگه می‌داریم. سپس از این آرایه‌ها را برای نمایه‌سازی استفاده می‌کنیم.
</font>
</p>

In [116]:
a = np.arange(12).reshape(4, 3)
print(a)
row = np.array([0, 2, 3, 2])
col = np.array([0, 2, 1, 0])
a[row, col]

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


array([ 0,  8, 10,  6])

<p dir=rtl style="direction: rtl;text-align: right;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazir" size=3 color='midnightblue'>
در ترکیب شدن آرایه های مربوط به بعدهای مختلف، خاصیت پخش آرایه ها برقرار است.
    </font>
</p>

<p dir=rtl style="direction: rtl;text-align: right;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazir" size=4>
گذاشتن np.newaxis در جایی از براکت، به معنای اضافه کردن یک بُعد با اندازه یک به آرایه در آنجا است.
    <br>
    برای مثال row[:, np.newaxis] معادل است با row.reshape(4, 1).
    </font>
</p>

In [117]:
a[row[:, np.newaxis], col]

array([[ 0,  2,  1,  0],
       [ 6,  8,  7,  6],
       [ 9, 11, 10,  9],
       [ 6,  8,  7,  6]])

<p dir=rtl style="direction: rtl;text-align: right;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazir" size=4>
هم‌چنین می‌توانیم ضمن نمایه‌سازی به این شیوه، آرایه مورد نظر را تغییر دهیم. مثلا با کد زیر می‌توانیم خانه‌های با مقدار زوج آرایه را ده برابر کنیم.
    </font>
</p>

In [118]:
a = np.array([2, 1, 3, 4, 5])
a[a%2 == 0] *= 10
print(a)

[20  1  3 40  5]


<p dir=rtl style="direction: rtl;text-align: right;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazir" size=4>
برای تکرار چند باره یک عملیات در یک خانه خاص از تابع عمومی at استفاده میکنیم. این تابع عملیات را به تعدادی که شماره خانه تکرار شده است انجام میدهد.
    </font>
</p>

<p dir=rtl style="direction: rtl;text-align: right;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazir" size=3 color='midnightblue'>
به خانه صفر 3 بار 5 را اضافه میکند، به خانه 1، 2 بار و به خانه 2، 1 بار.
    </font>
</p>

In [119]:
np.add.at(a, [0, 0, 0, 1, 1, 2], 5)
print(a)

[35 11  8 40  5]


<br>
<div dir=rtl id="start" style="direction:rtl;line-height:200%;">
	<font face="vazir" size=7 color='Red'>
    مرتب‌سازی و جبرخطی
    </font>
</div>

<br>
<div dir=rtl id="start" style="direction:rtl;line-height:200%;">
	<font face="vazir" size=6 color='Orange'>
    مرتب سازی
    </font>
</div>

<p dir=rtl style="direction: rtl;text-align: right;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazir" size=4>
در الگوریتم مرتب‌سازی درجی (insertion sort) پس از مرتب کردن عناصر قبل از عنصر iم، این عنصر تا جایی که کوچکتر از عنصر قبلی خود باشد با آن جابجا می‌شود و به این ترتیب در جای مناسب خود درج می‌شود. 
    </font>
</p>

In [120]:
def insertion_sort(a):
    for i in range(len(a)):
        j = i
        while j > 0 and a[j] < a[j-1]:
            a[j], a[j-1] = a[j-1], a[j]
            j -= 1         
            
a = np.array([7, 3, 11, 13, 5])
insertion_sort(a)
print(a)

[ 3  5  7 11 13]


<p dir=rtl style="direction: rtl;text-align: right;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazir" size=3 color='midnightblue'>
مرتبه زمانی این الگوریتم برای آرایه n تایی از O(n^2)
  است و مناسب آرایه‌های بزرگ نیست. به جهت پرتکرار بودن الگوریتم مرتب‌سازی در برنامه‌ها و لزوم بهینگی آن، الگوریتم‌های سریع‌تری چون مرتب‌سازی سریع (quick sort) در توابع آماده sort پایتون و نامپای پیاده‌سازی شده‌اند (مرتبه زمانی این الگوریتم‌ها از O(nlogn) است). به این ترتیب، برای مرتب‌سازی آرایه‌های نامپای از تابع np.sort استفاده می‌کنیم که آرایه را به صورت مرتب خروجی می‌دهد.
   </font>
</p>

In [121]:
a = np.array([5, 2, 9, 4, 1])
np.sort(a)

array([1, 2, 4, 5, 9])

<p dir=rtl style="direction: rtl;text-align: right;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazir" size=3 color='midnightblue'>
    عملیات مرتب‌سازی را می‌توان با استفاده از متد sort آرایه به صورت درجا هم انجام داد.
    </font>
</p>

In [122]:
a.sort()
print(a)

[1 2 4 5 9]


<p dir=rtl style="direction: rtl;text-align: right;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazir" size=3 color='midnightblue'>
    میتوانیم برای مرتب سازی axis هم مشخص کنیم تا در همون راستا مرتب کند.
    </font>
</p>

In [123]:
a = np.random.randint(0, 10, (4, 5))
print(a)

[[6 3 4 5 9]
 [0 4 3 2 1]
 [7 6 6 4 0]
 [7 6 6 6 1]]


In [124]:
np.sort(a,axis=0)

array([[0, 3, 3, 2, 0],
       [6, 4, 4, 4, 1],
       [7, 6, 6, 5, 1],
       [7, 6, 6, 6, 9]])

In [125]:
np.sort(a,axis=1)

array([[3, 4, 5, 6, 9],
       [0, 1, 2, 3, 4],
       [0, 4, 6, 6, 7],
       [1, 6, 6, 6, 7]])

<p dir=rtl style="direction: rtl;text-align: right;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazir" size=4>
تابع np.partition با ورودی گرفتن مقدار k، آرایه‌ای را خروجی می‌دهد که در آن، k+1 عنصرِ کوچک‌ترِ آرایه، پیش از سایر عناصر آمده‌اند.
    <br>
    با توجه به خطی بودن عملیات partition ، مرتبه زمانی این الگوریتم هم از O(nlogn) است.
    </font>
</p>

In [126]:
a = np.random.randint(0, 10, (4, 5))
print(a)

[[2 1 2 4 0]
 [5 5 1 6 0]
 [1 6 2 4 5]
 [9 7 1 8 1]]


In [127]:
np.partition(a, 2,axis=1)

array([[0, 1, 2, 4, 2],
       [0, 1, 5, 6, 5],
       [1, 2, 4, 6, 5],
       [1, 1, 7, 8, 9]])

<p dir=rtl style="direction: rtl;text-align: right;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazir" size=3 color='midnightblue'>
    عملگر argpartition مرتب میکند و اندیس آرایه اولیه را میدهد
    </font>
</p>

In [128]:
np.argpartition(a,2,axis=1)

array([[4, 1, 2, 3, 0],
       [4, 2, 1, 3, 0],
       [0, 2, 3, 1, 4],
       [2, 4, 1, 3, 0]], dtype=int64)

<p dir=rtl style="direction: rtl;text-align: right;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazir" size=4>
تابع np.argsort به جای آرایه مرتب شده، آرایه‌ای بر می‌گرداند که در خانه iم آن، شماره خانه iمین کوچک‌ترین عنصر آرایه قرار دارد. 
    </font>
</p>

In [129]:
a = np.array([5, 2, 7, 3, 1])
ind = np.argsort(a)
print(ind)

[4 1 3 0 2]


<br>
<div dir=rtl id="start" style="direction:rtl;line-height:200%;">
	<font face="vazir" size=6 color='Orange'>
    جبر خطی
    </font>
</div>

<p dir=rtl style="direction: rtl;text-align: right;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazir" size=4>
برای ضرب ماتریسی دو آرایه از توابع np.matmul , np.dot استفاده میکنیم. 
    </font>
</p>

In [130]:
x = np.array([1, 2, 3])
y = np.array([4, 5, 6])
print('x =', x)
print('y =', y)

x = [1 2 3]
y = [4 5 6]


In [131]:
np.matmul(x, y) # np.matmul(x,y) = a @ b

32

In [132]:
a = np.random.randint(1, 10, (3, 2))
b = np.random.randint(1, 10, (2, 3))
print(a)
print(b)

[[6 3]
 [5 9]
 [6 7]]
[[6 2 7]
 [8 8 1]]


In [133]:
np.matmul(x, a)

array([34, 42])

In [134]:
np.matmul(b,x)

array([31, 27])

In [135]:
np.dot(a,b) # np.dot(a,b) = a.dot(b)

array([[ 60,  36,  45],
       [102,  82,  44],
       [ 92,  68,  49]])

<p dir=rtl style="direction: rtl;text-align: right;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazir" size=4>
زیربخش linalg در نامپای برای گردآوری عملیات جبری روی ماتریس ها است.
    <br>
    برای مثال دو تابع det , inv به ترتیب، دترمینان و ماتریس معکوس یک ماتریس مربعی (با تعریف آرایه) را محاسبه میکنند.
    </font>
</p>

In [136]:
from numpy.linalg import inv, det
a = np.random.randn(4, 4)
print(a)

[[-0.27105384  0.44113455  0.36564294 -0.76724398]
 [-1.22188381 -0.81487745 -0.98462859 -0.16129166]
 [-0.24546808  0.74500184 -1.42373121 -1.93741905]
 [ 0.60685054 -0.20108201 -1.03793707  1.24279168]]


In [137]:
det(a)

-1.3200602229003648

In [138]:
inv(a)

array([[-2.86309129, -0.7960169 ,  0.55189066, -1.01049677],
       [ 4.01189154,  0.11518496, -0.40526504,  1.85993345],
       [-0.09025381, -0.16699237, -0.2591389 , -0.48136933],
       [ 1.97177852,  0.26786254, -0.55148142,  1.19697341]])

<br>
<div dir=rtl id="start" style="direction:ltr;line-height:200%;">
	<font face="vazir" size=7 color='Red'>
The END
    </font>
</div>